# Load tmuxline config: https://github.com/edkolev/tmuxline.vim
source-file ~/.tmuxline.snapshot

# Change prefix key
set-option -g prefix C-a

# Set default shell
set-option -g default-shell /usr/local/bin/fish

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Reorder window index automatically
set-option -g renumber-windows on

# Rename window based on current path
set-option -g status-interval 1
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# Enable vi mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
